ruby ob_control_downloads_stop.rb
ruby ob_control_fa_stop.rb
ruby ob_control_inventory_stop.rb
ruby ob_control_parser_stop.rb
ruby ob_control_return_stop.rb
ruby ob_control_return_upload_stop.rb
ruby ob_control_shipment_stop.rb
ruby ob_control_shipment_upload_stop.rb