development:
  adapter: "mysql2"
  encoding: "utf8"
  host: "127.0.0.1"
  database: "alm"
  username: "alm"
  password: "changeme"
  port: 3306
  #socket: /tmp/mysql.sock
  timeout: 5000
  mail_domain: "yourdomain.com"
  mail_host: "mail.yourdomain.com"
  mail_port: 587
  mail_authentication: :login # :plain, :login or :cram_md5

production:
  adapter: "mysql2"
  encoding: "utf8"
  host: "127.0.0.1"
  database: "alm"
  username: "alm"
  password: "changeme"
  port: 3306
  #socket: /tmp/mysql.sock
  timeout: 5000
  mail_domain: "yourdomain.com"
  mail_host: "mail.yourdomain.com"
  mail_port: 587
  mail_authentication: :login # :plain, :login or :cram_md5

test:
  adapter: "mysql2"
  encoding: "utf8"
  host: "127.0.0.1"
  database: "order_manager"
  username: "root"
  password: "NOT_CONFIGURED"
  port: 3306
  socket: /tmp/mysql.sock
  timeout: 5000

